[project]
name = "self-code-adk"
version = "0.1.0"
description = "ADK agent which help in analysing currently running multiagent app"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-adk>=0.3.0",
]

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]
