name: build and publish
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    name: python
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/project/self-code-adk
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2  # Fetch the last two commits to check for file changes

      - name: Check if pyproject.toml was modified
        id: check-pyproject
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "pyproject.toml"; then
            echo "pyproject_modified=true" >> $GITHUB_OUTPUT
          else
            echo "pyproject_modified=false" >> $GITHUB_OUTPUT
          fi

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests with coverage
        run: uv run pytest

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          fail_ci_if_error: false
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Build
        run: uv build
      
      - name: Publish
        if: steps.check-pyproject.outputs.pyproject_modified == 'true'
        run: uv publish
