name: build and publish
permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main
jobs:
  build-and-publish:
    name: python
    runs-on: ubuntu-latest
    environment: 
      name: pypi
      url: https://pypi.org/project/self-code-adk
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest

      - name: Build
        run: uv build
      
      - name: Publish
        run: uv publish
