name: test and build
permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - 'main'
jobs:
  build-and-test:
    name: python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: lint
        run: uv run black --check

      - name: Run tests
        run: uv run pytest

      - name: Build
        run: uv build
      